sonar.host.url=http://localhost:9000
sonar.token=squ_8de171e3b005d18faa17464ce53f068ae242b23a
sonar.projectKey=notedraftforge
sonar.projectName=notedraftforge
sonar.sources=src
sonar.tests=src,e2e
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts
sonar.exclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,src/ui/components/ui/**
sonar.javascript.environments=browser,node
sonar.javascript.lcov.reportPaths=coverage/lcov.info
