quarkus.application.name=ndf-gateway-auth
quarkus.http.port=8080

# SmallRye JWT Configuration
mp.jwt.verify.issuer=https://auth.notedraftforge.org
smallrye.jwt.sign.key=classpath:privateKey.pem
mp.jwt.verify.publickey.location=publicKey.pem

# OpenAPI / Swagger UI
quarkus.smallrye-openapi.path=/q/openapi
quarkus.swagger-ui.always-include=true
