quarkus.application.name=ndf-service-sync-vault
quarkus.http.port=8082

# Database & Flyway
quarkus.datasource.db-kind=postgresql
quarkus.datasource.devservices.enabled=true
quarkus.flyway.migrate-at-start=true
quarkus.hibernate-orm.database.generation=none

# MicroProfile REST Client for Sovereign GitHub Sync
quarkus.rest-client.github-api.url=https://api.github.com
quarkus.rest-client.github-api.scope=jakarta.inject.Singleton
